### ISSUE TITLE
Method properties does not seem to be catched

### ISSUE THREAD

**Issue by marlun** [romainl/ctags-patterns-for-javascript#14]
Method properties http://es6-features.org/#MethodProperties does not seem to be picked up by the available rules. In something like this:

    const obj = {
      foo () {
        console.log('bar')
      }
    }

Only "obj" will be picked up, not "foo".

**Comment by marlun** [comment]
Sorry I found the rule and the fact that no space is allowed after then name and before the (. But the regex do look like I'm supposed to have 0 or more spaces?

**Comment by marlun** [comment]
I guess something like

    --regex-javascript=/^[ \t]*\([A-Za-z0-9_$]\{1,\}\)[ \t]*(.*)[ \t]*[{]/\1/M,Method,Methods/b

would fix it but I'm not sure if it would collide with something else?

**Comment by marlun** [comment]
Created #15 if you want to use it, if not, feel free to close it.

**Comment by fabriziobertoglio1987** [comment]
I also tested this scenario and the only solution is finding a suitable alternative library

```javascript
class Test {
  method(param) { 
    console.log('test');
  }
}
```
