### ISSUE TITLE
Flow support

### ISSUE THREAD

**Issue by marbex7** [romainl/ctags-patterns-for-javascript#16]
I found this issue on the Flow repo and I was wondering if the ctags-patterns-for-javascript project might be a good way to solve the problem?

https://github.com/facebook/flow/issues/5322

**Comment by romainl** [comment]
I… don't see how ctags, my ctags config, and flow are related. Could you explain your vision?

**Comment by marbex7** [comment]
Flow allows types to be imported
```javascript
import type { something } from somewhere
```
See: https://flow.org/en/docs/types/modules/

When I use this form of the import statement with ctags to jump to the definition of 'something' I get 'tag not found'. All the other symbols I chose to inspect worked perfectly with ctags-patterns-for-javascript.

When I was researching the issue I encountered the above-mentioned facebook ticket, and I wondered if ctags-patterns-for-javascript might be the right place for a solution. Maybe an additional regex pattern? Please forgive if I have a misunderstanding of how this works.

**Comment by romainl** [comment]
OK! I get it, now. While that syntax is not *technically* JavaScript it *should* be possible to handle it here. But don't you also import `something` in a non-flow ctags-friendly way?

**Comment by marbex7** [comment]
Yes - I see your point - it's not actual Javascript. Maybe we need ctags-patterns-for-flow :-)

Regarding your question, usage-wise, there is not any necessity for another import. The example below is a typical usage (for me anyway):

```javascript
import type { something } from somewhere

function somefunc (): something {
    // return an instance of the something type perhaps from factory function ...
}
```
One thing I did notice - when trying to follow the 'something' symbol in the function defintion, ctags takes me off to the definition of a same-named but otherwise unrelated symbol in a different source file.

**Comment by romainl** [comment]
import type { something } from somewhere

should be easy to implement, but I could use a few realistic Flow samples in [`index.js`](https://github.com/romainl/ctags-patterns-for-javascript/blob/master/index.js) similar to the "imports" block.

Could you do it?

**Comment by marbex7** [comment]
Yes I will try as soon as I can.

**Comment by marbex7** [comment]
PR: https://github.com/romainl/ctags-patterns-for-javascript/pull/17

**Comment by danny-does-stuff** [comment]
It seems that to close this issue, we may just need to add the changes from #18 into the `ctagsrc` file. @the-code-robot do you have any more insight on this? Do you have ctags working with flow now?

**Comment by romainl** [comment]
Named flow imports have been supported for a while, now, they are now also mentioned in the `README`.
