### ISSUE TITLE
Make patterns more portable

### ISSUE THREAD

**Issue by romainl** [romainl/ctags-patterns-for-javascript#2]
See http://www.gnu.org/software/grep/manual/html_node/Basic-vs-Extended.html for a couple of advices.

**Comment by michael-coleman** [comment]
Would you consider something along the lines of the following a solution?
Taking [this regex](https://github.com/romainl/ctags-patterns-for-javascript/blob/master/.ctags#L32)

    --regex-javascript=/^[ \t]*([A-Za-z0-9_$]+)[ \t]*\(.*\)[ \t]*{/\1/M,Method,Methods/

I've rewritten it in the "basic posix" style:

    --regex-javascript=/^[ \t]*\([A-Za-z0-9_$]\+\)[ \t]*(.*)[ \t]*{/\1/M,Method,Methods/b

and added the `b` flag on the end  it seems to tell ctags to use posix basic for this regex only

it seems to work for me.
[updates to this comment: fixed regex]

**Comment by romainl** [comment]
Yes, forcing basic regex seems to be the right approach, here. Give me a week or two to find the time to work on that.

**Comment by michael-coleman** [comment]
Cool.
If it helps,  from all the javascript regexes [in this file](https://github.com/romainl/ctags-patterns-for-javascript/blob/master/.ctags)  I only found 10 or so regexes that broke on my ctags, the rest work fine.    

```
% ctags --version
Exuberant Ctags 5.9~svn20110310, Copyright (C) 1996-2009 Darren Hiebert
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```


here are the regexes that broke (or merely generated warnings):

    --regex-javascript=/^[ \t]*export[ \t]?({[ \t]*)*([A-Za-z0-9_\*]*[ \t]as[ \t])([A-Za-z0-9_]+)/\3/E,Export,Exports/
    --regex-javascript=/^[ \t]*export[ \t]?({[ \t]*)*([A-Za-z0-9_\*]*[ \t]as[ \t])*([A-Za-z0-9_]+),[ \t]*([A-Za-z0-9_\*]*[ \t]as[ \t])([A-Za-z0-9_]+)/\5/E,export,Exports/
    --regex-javascript=/^[ \t]*export[ \t]?({[ \t]*)*([A-Za-z0-9_\*]*[ \t]as[ \t])*([A-Za-z0-9_]+),[ \t]*([A-Za-z0-9_\*]*[ \t]as[ \t])*([A-Za-z0-9_]+),[ \t]*([A-Za-z0-9_\*]*[ \t]as[ \t])([A-Za-z0-9_]+)/\7/E,Export,Exports/
    
    --regex-javascript=/^[ \t]*(\*[ \t])([A-Za-z0-9_$]+)[ \t]*\(.*\)[ \t]*{/\2/G,Generator,Generators/
    
    --regex-javascript=/^[ \t]*import[ \t]?({[ \t]*)*([A-Za-z0-9_\*]*[ \t]as[ \t])([A-Za-z0-9_]+)/\3/I,Import,Imports/
    
    --regex-javascript=/^[ \t]*import[ \t]?({[ \t]*)*([A-Za-z0-9_\*]*[ \t]as[ \t])*([A-Za-z0-9_]+),[ \t]*([A-Za-z0-9_\*]*[ \t]as[ \t])([A-Za-z0-9_]+)/\5/I,Import,Imports/
    --regex-javascript=/^[ \t]*import[ \t]?({[ \t]*)*([A-Za-z0-9_\*]*[ \t]as[ \t])*([A-Za-z0-9_]+),[ \t]*([A-Za-z0-9_\*]*[ \t]as[ \t])*([A-Za-z0-9_]+),[ \t]*([A-Za-z0-9_\*]*[ \t]as[ \t])([A-Za-z0-9_]+)/\7/I,Import,Imports/
    
    --regex-javascript=/^[ \t]*this\.([A-Za-z0-9_$]+)[ \t]*=.*{$/\1/M,Method,Methods/
    --regex-javascript=/^[ \t]*([A-Za-z0-9_$]+)\(.*\)[ \t]*{/\1/M,Method,Methods/
    
    --regex-javascript=/^[ \t]*(var|let|const)[ \t]+([A-Za-z0-9_$]+)[ \t]*=[ \t]*{/\2/O,Object,Objects/


and here is the typical warning I would see:

> ctags: Warning: regcomp ^[      ]*([A-Za-z0-9_$]+)\(.*\)[       ]*{: Unmatched \{

**Comment by romainl** [comment]
Thank you, I will look into this as soon as possible.

**Comment by romainl** [comment]
@michael-coleman, I ported every pattern to basic regex. Please take a look at branch issue#2.
