### ISSUE TITLE
Functions with multi-line arguments are being recognised as properties, not methods

### ISSUE THREAD

**Issue by mulholo** [romainl/ctags-patterns-for-javascript#24]
The following code on a class is being recongised as a property, not a function/method
```javascript
// in some class

  someMethod = (
    one,
    two,
    three
  ) => {
    // body
  };
```

**Comment by romainl** [comment]
Modifying one of the "method" patterns to match this was relatively straightforward but it's still matched by my single overreaching "property" pattern so it appears both as a "M" and as a "P".

I will have to split that "property" pattern in two (at least) to make sure it correctly matches:

    foo.bar = (…
    this.baz = (…

and not:

    foo = (…

**Comment by romainl** [comment]
Could you take a look at the latest revision? It covers a lot more ground than what is discussed here but I think it works.

**Comment by mulholo** [comment]
Looks like that's registering the funcs as methods properly!

They appear to be folding in the wrong place (on the curly bracket line, not the first line of the method with the method name) but don't know if that's a ctag issue or a seperate fold issue.

**Comment by romainl** [comment]
Ctags doesn't deal with folding, so the folding issue is definitely elsewhere.

**Comment by mulholo** [comment]
Thought so. Thanks for the help!
