### ISSUE TITLE
ES6 class method support was lost

### ISSUE THREAD

**Issue by mvanderkamp** [romainl/ctags-patterns-for-javascript#25]
I'm not sure exactly when, but somewhere in the last several months the following regex pattern disappeared from the file that is now 'ctagsrc':

`--regex-javascript=/^[ \t]*\([A-Za-z0-9_$]\{1,\}\)(.*)[ \t]*[{]/\1/M,Method,Methods/b`

It is still listed in the readme though.

Without it, support for the following patterns is lost:

```
method_name() {
method_name(params) {
```

**Comment by romainl** [comment]
@mvanderkamp That line got lost to a botched refactoring. It's back.
