### ISSUE TITLE
doesn't extract

### ISSUE THREAD

**Issue by dlwe** [romainl/ctags-patterns-for-javascript#28]
async function foo() {
}

let bar;

**Comment by dlwe** [comment]
still doesn't work.

let bar;

**Comment by romainl** [comment]
Sorry, I didn't notice the `let bar;`. This should be fixed, now.

**Comment by dlwe** [comment]
doexn't extract let_declaration_inlined_3

let let_declaration_inlined_1, let_declaration_inlined_2 ,let_declaration_inlined_3;

**Comment by romainl** [comment]
Hmm… what did I do wrong?

**Comment by romainl** [comment]
@dlwe could you try last commit?

**Comment by dlwe** [comment]
It doesn't work.
Not 
let let_declaration_inlined_1, let_declaration_inlined_2, let_declaration_inlined_3;
But
let let_declaration_inlined_1, let_declaration_inlined_2 ,let_declaration_inlined_3;

Be aware of space and comma before let_declaration_inlined_3.

And last commit doesn't work with:
let
 let_declaration_inlined_4;

**Comment by romainl** [comment]
> Be aware of space and comma before let_declaration_inlined_3.

I see it, now.

> And last commit doesn't work with:
> let
> let_declaration_inlined_4;

Yes, I voluntarily limited it to three levels for the time being.

**Comment by romainl** [comment]
This should do it. Sorry for not noticing the bad spacing.
