### ISSUE TITLE
Please support Universal Ctags

### ISSUE THREAD

**Issue by alex-shamshurin** [romainl/ctags-patterns-for-javascript#29]
+

**Comment by romainl** [comment]
I don't use Universal Ctags so I don't have much of an incentive to make this project compatible. If you do, you are welcome to send PRs.

**Comment by alex-shamshurin** [comment]
So may be you should move to universal ctags ?

**Comment by romainl** [comment]
I have no reason to.

**Comment by alex-shamshurin** [comment]
Hmm, sounds like these are same. As far as I know Universal ctags is much better, isn't ?

**Comment by romainl** [comment]
Generally, I replace a tool when it stops working, not when a shinier tool appears. 

New users should definitely go with Universal, but Exuberant has been serving me well for over a decade so I have no need for a replacement.
