### ISSUE TITLE
"if" is matched

### ISSUE THREAD

**Issue by zjkdragon** [romainl/ctags-patterns-for-javascript#3]
![image](https://user-images.githubusercontent.com/5734130/34293932-61deaa94-e741-11e7-8b41-bb45a110456b.png)

**Comment by romainl** [comment]
Thanks. It's unfortunately not easy to negate something in the RE flavors used by Ctags so the "method" patterns currently also match `if`, `while` and `for`.

**Comment by romainl** [comment]
Hmm… actually, `if`, `while`, and `for` shouldn't be matched at all (they are not, here). Could you make sure you don't have multiple `.ctags` files and then try without a plugin?

**Comment by zjkdragon** [comment]
I know the reason.My code like this:
if() {
}
could be matched.
But like this:
if () {
}
could not be matched.

**Comment by zjkdragon** [comment]
I know the reason.My code like this:
```
if() {
}
```
could be matched.

But like this:
```
if () {
}
```
could not be matched.

**Comment by romainl** [comment]
`if` doesn't seem to be matched anymore. Closing this issue.
