### ISSUE TITLE
async / await support

### ISSUE THREAD

**Issue by justinabrahms** [romainl/ctags-patterns-for-javascript#30]
Doesn't look like there's support for async/await style functions. For instance, This isn't getting picked up:

```js
const myFn = async function({
 val1: mappingVal,
 val2,
 val3
}) {
  // ...
})
```

**Comment by romainl** [comment]
You are right. I plan to add a few TypeScript-oriented features this week-end and I will certainly find time to add this too.

**Comment by romainl** [comment]
@justinabrahms could you take a look at last commit (56ae576)?

**Comment by justinabrahms** [comment]
Works super well! Thanks so much.
