### ISSUE TITLE
Variable names starting with `_`

### ISSUE THREAD

**Issue by sparkcanon** [romainl/ctags-patterns-for-javascript#34]
Hi,

Thanks for your work on this.
So some of my variables/consts/lets/functions that start with an `_` are not recognized.

<img width="314" alt="Screenshot 2020-03-18 at 11 06 53" src="https://user-images.githubusercontent.com/41004069/76954644-96454b80-6908-11ea-8e7e-9b5f9115571d.png">

How do I get ctags to recognize these particular variables? I'd appreciate some pointers to achieve this.

**Comment by romainl** [comment]
Hi, names starting with an underscore are supported for variables but, for some reason, I've explicitly written the patterns for arrow functions to start with lowercase letters. This sounds silly in retrospect but I must have had… reasons.

Let me look into that.

**Comment by romainl** [comment]
Well, fuck GitHub for autoclosing issues on my behalf.

@sparkcanon could you try again with the new commit?

**Comment by sparkcanon** [comment]
Works very well now, thanks for the quick resolution. Appreciate your work on this.
