### ISSUE TITLE
Not recognizing everything

### ISSUE THREAD

**Issue by himat** [romainl/ctags-patterns-for-javascript#35]
Hi, I followed the instructions under the "Try" section of the readme.

After running `make tags`, the generated tags file only had this

```
!_TAG_FILE_FORMAT   2   /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED   1   /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME  Exuberant Ctags //
!_TAG_PROGRAM_URL   http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.8 //
Comp01  index.js    /^var Comp01 = styled(Box)`$/;" v
Constr_var  index.js    /^var Constr_var = function() {$/;" c
Constr_var.constr_var_meth  index.js    /^  this.constr_var_meth = function() {$/;" m
OUT Makefile    /^OUT = @echo `date +[\\ %F\\ -\\ %T\\ ]`$/;"   m
SHELL   Makefile    /^SHELL := \/bin\/bash$/;"  m
class_constr_meth   index.js    /^      this.class_constr_meth = function(){$/;"    f
class_meth_equal    index.js    /^  class_meth_equal = function($/;"    f
const   index.js    /^const Constr_const = function() {$/;" c
const   index.js    /^const function_const = function() {$/;"   f
const.body  test.js /^    const config = { method, body: JSON.stringify(body) }$/;" p
const.constr_const_meth index.js    /^  this.constr_const_meth = function() {$/;"   m
function_basic  index.js    /^function function_basic() {$/;"   f
let index.js    /^let Constr_let = function() {$/;" c
let.constr_let_meth index.js    /^  this.constr_let_meth = function() {$/;" m
obj_lit.obj_lit_prop_array  index.js    /^  obj_lit_prop_array: [$/;"   p
obj_lit.obj_lit_prop_number index.js    /^  obj_lit_prop_number: 123,$/;"   p
obj_lit.obj_lit_prop_string index.js    /^  obj_lit_prop_string : "eee",$/;"    p
obj_lit_inline.obj_lit_inline_prop  index.js    /^var obj_lit_inline = { obj_lit_inline_prop: 1 };$/;"  p
this_prop.this_inner_prop   index.js    /^  this_inner_prop: "bar"$/;"  p
this_prop_method    index.js    /^this.this_prop_method = function($/;" f
var_declaration index.js    /^var var_declaration;$/;"  v
var_declaration_inlined_1_of_2  index.js    /^var var_declaration_inlined_1_of_2, var_declaration_inlined_2_of_2;$/;"   v
var_declaration_inlined_1_of_2_trailing_space   index.js    /^var var_declaration_inlined_1_of_2_trailing_space , var_declaration_inlined_2_of_2_trailing_space ;$/;"   v
var_declaration_inlined_1_of_3  index.js    /^var var_declaration_inlined_1_of_3, var_declaration_inlined_2_of_3, var_declaration_inlined_3_of_3;$/;"   v
var_declaration_inlined_1_of_3_trailing_space   index.js    /^var var_declaration_inlined_1_of_3_trailing_space , var_declaration_inlined_2_of_3_trailing_space , var_declaratio
n_inlined_3_of_3_trailing_space ;$/;"   v
var_declaration_trailing_space  index.js    /^var var_declaration_trailing_space ;$/;"  v
var_var_regexp  index.js    /^var var_var_regexp = \/regexp\/;$/;"  v
```

Here is my `ctags --version`
```
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Sep 17 2017, 20:48:43
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex
```

How do I go about debugging why it isn't recognizing all the patterns?

**Comment by romainl** [comment]
The `tags` file is supposed to have 212 lines.

What OS do you use? How did you install Ctags?

**Comment by himat** [comment]
MacOS Mojave 10.14.5
Installed ctags via `brew install ctags`

**Comment by romainl** [comment]
Looking back at the snippet you posted I see that the "kind" letters at the end of each line are all lowercase. The `ctagsrc` file in this repo disables the default lowercase kinds and creates custom uppercase ones so it looks to me like that `ctagsrc` file is not honoured.

Experiments on my end:

* Tried again with current `Makefile` and current `ctags` provided by MacPorts

        $ rm tags && make tags

  212 lines,
  only uppercase kinds.

* Tried again with [the `ctags` provided by Homebrew](https://homebrew.bintray.com/bottles/ctags-5.8_1.mojave.bottle.2.tar.gz):

        $ rm tags && /Users/romainl/Downloads/ctags/5.8_1/bin/ctags --options=./ctagsrc index.js

  212 lines,
  only uppercase kinds.

From where I stand, the version of `ctags` is irrelevant and the `Makefile` is sound, so I wonder how it ends up *not* using the provided `ctagsrc`.

Can you run the following command from the root of the repo?

    $ rm tags && ctags --options=./ctagsrc index.js

**Comment by himat** [comment]
Interesting, I ran that 

and got 
```
 !!! index.js    /^\/\/ !!!: dear god!$/;"   T
 !_TAG_FILE_FORMAT   2   /extended format; --format=1 will not append ;" to lines/
 !_TAG_FILE_SORTED   1   /0=unsorted, 1=sorted, 2=foldcase/
 !_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
 !_TAG_PROGRAM_NAME  Exuberant Ctags //
 !_TAG_PROGRAM_URL   http://ctags.sourceforge.net    /official site/
 !_TAG_PROGRAM_VERSION   5.8 //
 ??? index.js    /^\/\/ ???: what the flying fuck?$/;"   T
 BUG index.js    /^\/\/ BUG: there's really something fishy about this$/;"   T
 ClassName   index.js    /^class ClassName {$/;" C
 Comp01  index.js    /^var Comp01 = styled(Box)`$/;" S
 Comp02  index.js    /^let Comp02 = styled(Box)`$/;" S
 Comp03  index.js    /^const Comp03 = styled(Box)`$/;"   S
 Comp04  index.js    /^var Comp04 = createGlobalStyle`$/;"   S
 Comp05  index.js    /^let Comp05 = createGlobalStyle`$/;"   S
 Comp06  index.js    /^const Comp06 = createGlobalStyle`$/;" S
... [omitting many lines]
var_declaration_inlined_1_of_3_trailing_space   index.js    /^var var_declaration_inlined_1_of_3_trailing_space , var_declaration_inlined_2_of_3_trailing_space , var_declaration_inlined_3_of_3_trailing_space ;$/;"   V
var_declaration_inlined_2_of_2  index.js    /^var var_declaration_inlined_1_of_2, var_declaration_inlined_2_of_2;$/;"   V
var_declaration_inlined_2_of_2_trailing_space   index.js    /^var var_declaration_inlined_1_of_2_trailing_space , var_declaration_inlined_2_of_2_trailing_space ;$/;"   V
var_declaration_inlined_2_of_3  index.js    /^var var_declaration_inlined_1_of_3, var_declaration_inlined_2_of_3, var_declaration_inlined_3_of_3;$/;"   V
var_declaration_inlined_2_of_3_trailing_space   index.js    /^var var_declaration_inlined_1_of_3_trailing_space , var_declaration_inlined_2_of_3_trailing_space , var_declaration_inlined_3_of_3_trailing_space ;$/;"   V
var_declaration_inlined_3_of_3  index.js    /^var var_declaration_inlined_1_of_3, var_declaration_inlined_2_of_3, var_declaration_inlined_3_of_3;$/;"   V
var_declaration_inlined_3_of_3_trailing_space   index.js    /^var var_declaration_inlined_1_of_3_trailing_space , var_declaration_inlined_2_of_3_trailing_space , var_declaration_inlined_3_of_3_trailing_space ;$/;"   V
var_declaration_trailing_space  index.js    /^var var_declaration_trailing_space ;$/;"  V
var_var_regexp  index.js    /^var var_var_regexp = \/regexp\/;$/;"  V
```

But the number of lines is only 209
```
$ wc -l tags
     209 tags
```

Running `make` now also works and produces the same result with 209 lines. Maybe I hadn't properly removed my `~/.ctags` file somehow before when I ran make.

Here is the full file if you want to see what could be the 3 missing lines. https://pastebin.com/n3SRfWVq

**Comment by romainl** [comment]
Thank you for the pastebin. Comparing to my local `tags` shows an interesting difference:

<img width="1920" alt="Capture d’écran 2020-04-22 à 11 05 10" src="https://user-images.githubusercontent.com/344335/79963054-2b4bdf00-8489-11ea-971a-a3681c5f31c2.png">

It looks like I have duplicate entries marked as both variables and functions.

Thank you for this, I will look into it.

**Comment by romainl** [comment]
Hmm, it turns out my local `ctagsrc` had unfinished experimental stuff in it. Stashing it removed those three additional lines.

It looks like we are good, now.

**Comment by himat** [comment]
Perhaps this is not built into your ctagsrc commands yet, but why does this kind of import not generate tags?

`import imp23`

I cannot jump to the `imp23` tag since there is no tag found for it.

Also a very common import that doesn't work is `import { imp44 } from ok`

**Comment by romainl** [comment]
The logic is explained in the `README.md`: I only tag *named* things.

In the following example, the import is not named at all. There is no point tagging it because it is already tagged elsewhere:

    import { foo } from './bim/boom';

In the following example there could be discussion because we import the default export and we might call it however we want. I opted for the idealistic approach: give it the same name as the export:

    import foo from './bim/boom';

**Comment by himat** [comment]
My use case though is that I don't want to tag all the libraries in my `node_modules/` dir. 
I have `--exclude=node_modules/` in my `ctags` file by default.

For example, if I have this in one of my files `import { useQuery } from "@apollo/react-hooks"`, it does generate the tags to go to `useQuery` within the `react-hooks` source code, but that isn't that useful for me. 

If I am calling `useQuery` in my code somewhere
```
 const { loading, error, data } = useQuery(...)
```
then, when I click on useQuery expecting to go to its tag, I just want to jump to the top of this current file instead of vim opening the source file.

However, I do agree with what you're saying for local imports
`import Table from "../Table";`
In this case, I probably would want the tag to go to my local Table.js file since it's my own code.

What would be a good way to keep the original tags for local files, but not for imported libraries?

**Comment by romainl** [comment]
I see.

I index `node_modules/` so I can jump anywhere in the project and its dependencies. In my mind, the import is just an implementation detail as long as it doesn't actively rename things. When I press `<C-]>` on `Foo` I would expect to jump to its definition (where the interesting stuff is) rather than its import (which doesn't provide much information). If I want to jump to the first occurrence of the keyword under the cursor I do `gD`.

> What would be a good way to keep the original tags for local files, but not for imported libraries?

The regex engine doesn't do back references so I can't make any decision based on what kind of import we have. Even if I could, the Node module resolution mechanism is so permissive that it would be a nightmare (is `foo` an absolute import, an npm import, or a node import? this is doable with code but certainly not with BRE).
