### ISSUE TITLE
Unknown tag kind encountered: "A". Your ctags and Tagbar configurations are out of sync! Please read ':help tagbar-extend'.

### ISSUE THREAD

**Issue by Fenriuz** [romainl/ctags-patterns-for-javascript#39]
The command ctgas ctags --list-kinds = javascript shows me everything correctly and when using the command ctags -R it correctly creates the tags, but when using the ctags with preservim/tagbar it shows me that error.

I don't know if I should configure something else in the tagbar.

![image](https://user-images.githubusercontent.com/63080658/104108193-4b763500-5288-11eb-942c-fa9506c83041.png)

**Comment by romainl** [comment]
> I don't know if I should configure something else in the tagbar.

Yes, the two-steps method is described [in tagbar's documentation](https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1590):

1. [Configure ctags](https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1608-L1639), this is what this project tries to do.
2. [Tell tagbar about that configuration](https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1641-L1665), this is your responsibility.

It should look something like:

    let g:tagbar_type_javascript = {
            \ 'ctagstype' : 'javascript',
            \ 'kinds'     : [
                \ 'T:Tags',
                \ 'A:Arrays:,
                \ 'O:Objects',
                \ 'P:Properties',
                \ 'G:Generators',
                \ 'F:Functions',
                \ 'C:Classes',
                \ 'M:Methods',
                \ 'V:Variables',
                \ 'I:Imports',
                \ 'E:Exports',
                \ 'S:Styled Components',
            \ ],
            \ 'sort'    : 0,
    }

This is untested, as I don't use that plugin, but it should put you on the right track.

**Comment by Fenriuz** [comment]
> > I don't know if I should configure something else in the tagbar.
> 
> Yes, the two-steps method is described [in tagbar's documentation](https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1590):
> 
> 1. [Configure ctags](https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1608-L1639), this is what this project tries to do.
> 2. [Tell tagbar about that configuration](https://github.com/preservim/tagbar/blob/master/doc/tagbar.txt#L1641-L1665), this is your responsibility.
> 
> It should look something like:
> 
> ```
> let g:tagbar_type_javascript = {
>         \ 'ctagstype' : 'javascript',
>         \ 'kinds'     : [
>             \ 'T:Tags',
>             \ 'A:Arrays:,
>             \ 'O:Objects',
>             \ 'P:Properties',
>             \ 'G:Generators',
>             \ 'F:Functions',
>             \ 'C:Classes',
>             \ 'M:Methods',
>             \ 'V:Variables',
>             \ 'I:Imports',
>             \ 'E:Exports',
>             \ 'S:Styled Components',
>         \ ],
>         \ 'sort'    : 0,
> }
> ```
> 
> This is untested, as I don't use that plugin, but it should put you on the right track.

Thank you very much, solve my problem.
Just out of curiosity, what plugin do you use?
Maybe tagbar is not what I'm looking for.

**Comment by romainl** [comment]
I only use Vim's built-in tags-related commands, sometimes via custom mappings as I'm not particularly interested by an always-on outline of my program.

This is the full extent of my tags-related configuration:

    " In vimrc
    " Tell Vim to look for "tags" files:
    "   - in the directory of the current file and its parent, recursively
    "   - in the working directory and its parents, recursively
    "   - in "node_modules/"
    set tags=./tags;,tags;,node_modules/tags

    " use regexp search for tag names instead of whole-word search
    " :tjump/:ptjump are my go-to commands because they act 
    " like :tselect/:ptselect if there are multiple tags and like :tag/:ptag if there is only one
    nnoremap ,j :tjump /
    nnoremap ,p :ptjump /

    " convenient mappings for finger-breaking commands
    nnoremap g$ g<C-]>
    nnoremap gù <C-w>g}

**Comment by Fenriuz** [comment]
I get it, I will use that same configuration. Thank you.
