### ISSUE TITLE
universal ctags: ctags: Kind letter 'F' used in regex definition "^[     ]*function[     ]*\([A-Za-z0-9_$]\{1,\}\)[      (]" of JavaScript language is reserved in ctags main

### ISSUE THREAD

**Issue by hatelove85911** [romainl/ctags-patterns-for-javascript#9]
I got the following error when I use it with universal ctags:

`ctags: Kind letter 'F' used in regex definition "^[     ]*function[     ]*\([A-Za-z0-9_$]\{1,\}\)[      (]" of JavaScript language is reserved in ctags main`

**Comment by romainl** [comment]
From the README:

> These patterns are only usable with Exuberant Ctags. Universal Ctags is not currently supported.

**Comment by angorf** [comment]
@hatelove85911 I've made a fork to make the rules compatible with Universal Ctags in case you're interested: https://github.com/agorf/ctags-patterns-for-javascript
